apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: transformer
  name: transformer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transformer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transformer
    spec:
      containers:
      - image: cmwylie19/transformer:0.0.1
        name: transformer
        command: ["./transformer","--port","50051"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 50051
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: transformer
  name: transformer
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: transformer
status:
  loadBalancer: {}
