apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: transformer
  name: transformer
  namespace: pepr-system
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: transformer
status:
  loadBalancer: {}
