name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    
    - name: Verify commit signature
      run: git log -1 --pretty=%G? ${{ github.sha }} | grep -qE '^U?$' || (echo "ERROR: Commit must be signed." && exit 1)
    
    - name: Install dependencies
      run: npm install
    
    - name: Run unit tests
      run: npx jest

    - name: Verify commit messages
      run: |
        commit_message="$(git log --format=%B -n 1 ${{ github.sha }})"
        echo "$commit_message" | grep -qiE '^(feat|fix|chore|docs|refactor|style|test)(\([^)]+\))?: .+$' || (echo "ERROR: Invalid commit message format." && exit 1)