apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: debugger
  name: debugger
  namespace: pepr-system
spec:
  containers:
  - image: cmwylie19/grpcurl-debugger:0.0.1
    name: debugger
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
